title: <repo>
description: a GH Pages installation
url: "https://rkooyenga.github.io"
baseurl: "/<repo>"
encoding: utf-8
lang: en-US
name: rkooyenga.github.io
avatar: 
logo: https://avatars.githubusercontent.com/u/6174603
picture: https://avatars.githubusercontent.com/u/9654073
fonts: https://rkooyenga.github.io/fonts
author: 
  name: Ray Kooyenga
  email: gmc5oz4k7@mozmail.com
remote_theme: jekyll/minima
minima:
  skin: dark
  date_format: "%a, %b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/rkooyenga" }
    - { platform: twitter, user_url: "https://twitter.com/rayktweets" }
#    - { platform: codepen, user_url: "https://codepen.io/deadflowers" }
    - { platform: imdb, user_url: "https://imdb.com/name/nm15105839" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ray-kooyenga-0a4753176" }
#    - { platform: tidal, user_url: "https://tidal.com/browse/user/170928610" }
#    - { platform: threads, user_url: "https://www.threads.net/@raykooyenga" }
#    - { platform: instagram, user_url: "https://www.instagram.com/raykooyenga" }
    - { platform: youtube, user_url: "https://www.youtube.com/@raykooyenga" }

twitter_username: rayktweets
github_username: rkooyenga
#codepen_username: deadflowers
twitter: rayktweets
#github: rkooyenga
#codepen: deadflowers
#imdb: nm15105839
#instagram: raykooyenga
youtube: raykooyenga
#threads: raykooyenga
#tidal: 170928610
#linkedin: ray-kooyenga-0a4753176
#medium:

#gravatar:
orcid: https://orcid.org/0009-0007-8239-4582

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pwa-plugin
  - jekyll-admin
#  - jekyll-paginate  
  
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

  # PAGINATION
#permalink: /blog/:categories/:year/:month/:day/:title.html
#paginate: 10
#paginate_path: "blog/:num"
#paginate_category: "blog"
#gems: [jekyll-paginate]

#links_to_prev_next: true

# Header and footer text
footer_text: made with github pages, jekyll, and some typing
